export const SEARCH_ACTION_TYPES = {
  SET_HEROS_MAP_STARTED: "SET_HEROS_MAP_STARTED",
  SET_HEROS_MAP_SUCCESS: "SET_HEROS_MAP_SUCCESS",
  SET_HEROS_MAP_FAILURE: "SET_HEROS_MAP_FAILURE",
  SET_SEARCH_STRING: "SET_SEARCH_STRING",
  SET_CURRENT_HERO: "SET_CURRENT_HERO",
};
